CREATE TABLE forma_pagamento
(
    id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    descricao varchar(255),

    PRIMARY KEY (id)
);

CREATE TABLE grupo
(
    id   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome varchar(80),

    PRIMARY KEY (id)
);

CREATE TABLE permissao
(
    id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome      varchar(80),
    descricao varchar(255),

    PRIMARY KEY (id)
);

CREATE TABLE restaurante
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY,
    nome                 varchar(80),
    taxa_frete           NUMERIC,
    endereco_cep         varchar(80),
    endereco_logradouro  varchar(80),
    endereco_numero      varchar(10),
    endereco_complemento varchar(255),
    endereco_bairro      varchar(80),
    data_cadastro        timestamp,
    data_atualizacao     timestamp,
    endereco_cidade_id   bigint,
    cozinha_id           bigint,

    CONSTRAINT fk_endereco_cidade_id FOREIGN KEY (endereco_cidade_id) REFERENCES algafood.cidade (id),
    CONSTRAINT fk_cozinha_id FOREIGN KEY (cozinha_id) REFERENCES algafood.cozinha (id),

    PRIMARY KEY (id)
);

CREATE TABLE produto
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    nome           varchar(80),
    descricao      varchar(255),
    preco          NUMERIC,
    ativo          boolean,
    restaurante_id bigint,

    CONSTRAINT fk_restaurante_id FOREIGN KEY (restaurante_id) REFERENCES algafood.restaurante (id),

    PRIMARY KEY (id)
);

CREATE TABLE usuario
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    nome          varchar(80),
    email         varchar(80),
    senha         varchar(80),
    data_cadastro timestamp,

    PRIMARY KEY (id)
);

CREATE TABLE grupo_permissao
(
    grupo_id     bigint NOT NULL,
    permissao_id bigint NOT NULL,

    CONSTRAINT fk_grupo_id FOREIGN KEY (grupo_id) REFERENCES algafood.grupo (id),
    CONSTRAINT fk_permissao_id FOREIGN KEY (permissao_id) REFERENCES algafood.permissao (id)
);

CREATE TABLE usuario_grupo
(
    usuario_id bigint NOT NULL,
    grupo_id   bigint NOT NULL,

    CONSTRAINT fk_usuario_id FOREIGN KEY (usuario_id) REFERENCES algafood.usuario (id),
    CONSTRAINT fk_grupo_id FOREIGN KEY (grupo_id) REFERENCES algafood.grupo (id)
);

CREATE TABLE restaurante_forma_pagamento
(
    restaurante_id     bigint NOT NULL,
    forma_pagamento_id bigint NOT NULL,

    CONSTRAINT fk_restaurante_id FOREIGN KEY (restaurante_id) REFERENCES restaurante (id),
    CONSTRAINT fk_forma_pagamento_id FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento (id)
);