CREATE TABLE pedido
(
    id                   bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sub_total            NUMERIC      NOT NULL,
    taxa_frete           NUMERIC      NOT NULL,
    valor_total          NUMERIC      NOT NULL,

    forma_pagamento_id   bigint       NOT NULL,
    restaurante_id       bigint       NOT NULL,
    usuario_cliente_id   bigint       NOT NULL,

    endereco_cidade_id   bigint       NOT NULL,
    endereco_cep         varchar(60)  NOT NULL,
    endereco_logradouro  varchar(100) NOT NULL,
    endereco_numero      varchar(20)  NOT NULL,
    endereco_bairro      varchar(60)  NOT NULL,
    endereco_complemento varchar(60),

    status               varchar(10)  NOT NULL,
    data_criacao         timestamp    NOT NULL,
    data_confirmacao     timestamp,
    data_cancelamento    timestamp,
    data_entrega         timestamp,

    PRIMARY KEY (id),

    CONSTRAINT fk_pedido_endereco_cidade_id FOREIGN KEY (endereco_cidade_id) REFERENCES cidade (id),
    CONSTRAINT fk_pedido_forma_pagamento_id FOREIGN KEY (forma_pagamento_id) REFERENCES forma_pagamento (id),
    CONSTRAINT fk_pedido_restaurante_id FOREIGN KEY (restaurante_id) REFERENCES restaurante (id),
    CONSTRAINT fk_pedido_cliente_id FOREIGN KEY (usuario_cliente_id) REFERENCES usuario (id)
);

CREATE TABLE item_pedido
(
    id             bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    quantidade     bigint  NOT NULL,
    preco_unitario NUMERIC NOT NULL,
    preco_total    NUMERIC NOT NULL,
    observacao     varchar(255) NULL,

    produto_id     bigint  NOT NULL,
    pedido_id      bigint  NOT NULL,

    PRIMARY KEY (id),
    UNIQUE (pedido_id, produto_id),

    CONSTRAINT fk_item_pedido_produto_id FOREIGN KEY (produto_id) REFERENCES produto (id),
    CONSTRAINT fk_item_pedido_pedido_id FOREIGN KEY (pedido_id) REFERENCES pedido (id)
);